---
on:
    pull_request:
        branches:
        - develop
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Setup dotnet
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: | 
              9.0.x
        - uses: actions/checkout@v5
        - name: restore
          run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj
        - name: build
          run: dotnet build --configuration Debug src/Presentation/Nop.Web/Nop.Web.csproj
        
          
		- name:upload test result 
		  run: dotnet test --logger:"trx;LogFilePrefix=testResults" src/Tests/Nop.Tests/Nop.Tests.csproj in
        - name: publish
          run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published
		- name: Create zip
          run: |
          mkdir -p published
          cp -r build/libs/* published/
          zip -r published.zip published

        - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: published.zip
		
		
