name: Build & Upload Artifact

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Checkout source
        uses: actions/checkout@v5

      - name: Restore
        run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

      - name: Build
        run: dotnet build --configuration Debug src/Presentation/Nop.Web/Nop.Web.csproj

      - name: Run tests (with trx logger)
        run: dotnet test --logger:"trx;LogFilePrefix=testResults" src/Tests/Nop.Tests/Nop.Tests.csproj

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/*.trx'

      - name: Publish
        run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published

      - name: Create zip
        run: |
          zip -r published.zip published

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-artifact
          path: published.zip

		
